# Site settings
title: Les Petites Baies Noires
long_title: les petites baies noires
name: Jean-Marie ESPEUT
email: contact@lespetitesbaiesnoires.com
phone:
  long: "(00 33)6 52 56 88 70"
  short: "+33652568870"
address: "17 Ch du pont de Jean Petit<br />11200 CONILHAC-CORBIERES"

baseurl: "/" 
url: "http://www.lespetitesbaiesnoires.com" # the base hostname & protocol for your site

defaults:
  - scope:
      path: "img/photos"
    values:
      image: true

exclude:
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - localbuild.sh
  - travis
  - CNAME
  - google*.html
  - extract_traduction.sh


# Build settings
markdown: kramdown

plugins: [jekyll-paginate-v2]

plugins_dir:
  - jekyll-paginate-v2

permalink: /post/:year/:month/:title.html

pagination:
  enabled: true
  debug: true
  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'
  per_page: 3

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  locale: ''
 # Optional,omit or set both before and after to zero to disable.
 # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2

  extension: html
  indexpage: 'index'
